package com.multilive.agent
import android.app.*
import android.content.*
import android.os.IBinder
import kotlinx.coroutines.*
class AgentService:Service(){private val scope=CoroutineScope(SupervisorJob()+Dispatchers.IO);private lateinit var prefs:AgentPrefs;private lateinit var api:ApiClient;private lateinit var tts:TtsEngine
 override fun onCreate(){super.onCreate();prefs=AgentPrefs(this);api=ApiClient(prefs);tts=TtsEngine(this);channel();startForeground(7,notification("Agent connected"));scope.launch{loop()}}
 private suspend fun loop(){while(isActive){try{val m=DeviceMetrics.read(this@AgentService);val net=NetworkMetrics.read(this@AgentService);val media=MediaPlaylistStore(this@AgentService);m.put("network",net);m.put("uploadMbps",net.optDouble("linkUpMbps",0.0));m.put("mediaItems",media.list().size);m.put("mediaLoop",media.loop);api.heartbeat(m);val a=api.commands();if(a!=null)for(i in 0 until a.length()){val c=a.getJSONObject(i);when(c.optString("type")){"remote_handoff"->notifyRemote(c.optJSONObject("payload")?.optString("sessionId")?:"");"tts_speak"->{val p=c.optJSONObject("payload");tts.speak(p?.optString("text")?:"",p?.optString("lang","th-TH")?:"th-TH",(p?.optDouble("rate",1.0)?:1.0).toFloat(),(p?.optDouble("pitch",1.0)?:1.0).toFloat())};"ops_alert"->{notifyOps(c.optJSONObject("payload"))};"media_play","media_next","media_pause"->{MediaCommandStore(this@AgentService).set(c.optString("type"));notifyMedia(c.optString("type"))}};api.ack(c.getString("id"))}}catch(_:Exception){};delay(15000)}}
 private fun channel(){getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel("agent","Multi Live Agent",NotificationManager.IMPORTANCE_LOW));getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel("urgent","Challenge / Remote",NotificationManager.IMPORTANCE_HIGH))}
 private fun notification(t:String)=Notification.Builder(this,"agent").setContentTitle("Multi Live Agent").setContentText(t).setSmallIcon(android.R.drawable.presence_online).build()
 private fun notifyOps(p:org.json.JSONObject?){val title=p?.optString("title","Live operations alert")?:"Live operations alert";val msg=p?.optString("message","Operator attention required")?:"Operator attention required";val sev=p?.optString("severity","warning")?:"warning";val pi=PendingIntent.getActivity(this,0,Intent(this,MainActivity::class.java),PendingIntent.FLAG_IMMUTABLE);getSystemService(NotificationManager::class.java).notify(97,Notification.Builder(this,"urgent").setContentTitle(title).setContentText("${sev.uppercase()} • $msg").setStyle(Notification.BigTextStyle().bigText(msg)).setSmallIcon(android.R.drawable.ic_dialog_alert).setContentIntent(pi).setAutoCancel(true).build())}
 private fun notifyMedia(action:String){val pi=PendingIntent.getActivity(this,0,Intent(this,MediaPreviewActivity::class.java),PendingIntent.FLAG_IMMUTABLE);getSystemService(NotificationManager::class.java).notify(98,Notification.Builder(this,"urgent").setContentTitle("Media schedule ready").setContentText(action.replace("media_","").uppercase()+" requested — tap to open preview").setSmallIcon(android.R.drawable.ic_media_play).setContentIntent(pi).setAutoCancel(true).build())}
 private fun notifyRemote(sessionId:String){prefs.pendingRemoteSession=sessionId;val pi=PendingIntent.getActivity(this,0,Intent(this,MainActivity::class.java),PendingIntent.FLAG_IMMUTABLE);getSystemService(NotificationManager::class.java).notify(99,Notification.Builder(this,"urgent").setContentTitle("Remote assistance requested").setContentText("Open the agent for human handoff").setSmallIcon(android.R.drawable.ic_dialog_alert).setContentIntent(pi).setAutoCancel(true).build())}
 override fun onDestroy(){scope.cancel();tts.shutdown();super.onDestroy()};override fun onBind(i:Intent?):IBinder?=null
 companion object{fun start(c:Context){c.startForegroundService(Intent(c,AgentService::class.java))}}
}
